apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop-dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: shopmini
    newName: shopmini          # image nạp bằng scripts/load-image.sh (kind load)
    newTag: lab05
secretGenerator:
  - name: shopmini-db
    envs: [db.env]             # file này KHÔNG commit (xem db.env.example)
patches:
  - target: { kind: ConfigMap, name: shopmini-config }
    patch: |-
      - op: replace
        path: /data/CHAOS_ENABLED
        value: "true"
  - target: { kind: Deployment, name: shopmini }
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1version
        value: lab05
