# AppProject giới hạn: chỉ được deploy từ repo của bạn, chỉ vào namespace shop-*
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: shop
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # project phải có trước các Application
spec:
  description: shopmini environments
  sourceRepos: ["https://github.com/YOUR_GITHUB_USER/devops-labs.git"]
  destinations:
    - { server: https://kubernetes.default.svc, namespace: "shop-*" }
  clusterResourceWhitelist:
    - { group: "", kind: Namespace }
  namespaceResourceBlacklist:
    - { group: "", kind: ResourceQuota }
  orphanedResources: { warn: true }
