apiVersion: v1
kind: Namespace
metadata:
  name: shop-dev
  labels:
    # Pod Security Admission: từ chối mọi pod không đạt chuẩn "restricted"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
